#!/usr/bin/env python3

from docx import Document
from oms import * 

document = Document()

document.add_paragraph("This is a paragraph")
document.add_paragraph("This is a paragraph")
document.add_page_break()
document.add_paragraph("This is a paragraph")

document.save("manuscript.docx")

reader.read("../example")


