#!/usr/bin/env python3

import os
import openms


print("Kicking tires ...")
openms.test.kick_tires()

# overall state
msdir  = "../example"
msfile = "manuscript.json"
afile  = "author.json"

# export docx
ofile  = "omstest_manuscript.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))

# export docx with notes
ofile  = "omstest_manuscript_all.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --chaptersummary --filescenesep --quote --synopsis --notes --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))
