#!/usr/bin/env python3

import os
import oms


print("Kicking tires ...")
# oms.word.kick_tires()
oms.test.kick_tires()

# overall state
msdir  = "../example"
msfile = "manuscript.json"
afile  = "author.json"

# manuscript to csv
ofile = "omstest_manuscript.csv"
print("Testing creation of manuscript csv file")
print("    writing file: {}".format(ofile))
oms.core.manuscript_to_csv(msdir, msfile, afile, ofile)

# csv to manuscript 
ofile   = "omstest_manuscript.json"
csvfile = "../example/outline.csv"
print("Testing creation of manuscript json from csv file")
print("    writing file: {}".format(ofile))
oms.core.csv_to_manuscript(csvfile, ofile)

# export docx
# ofile  = "omstest_manuscript.docx"
# print("Testing export of docx file")
# print("    writing file: {}".format(ofile))
# oms.word.write_docx(msdir, msfile, afile, ofile)

ofile = "omstest_manuscript.rtf"
print("Running oms2rtf")
os.system("./oms2rtf --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {} --footnotes".format(msdir, msfile, afile, ofile))

ofile = "omstest_manuscript_filescene.rtf"
print("Running oms2rtf")
os.system("./oms2rtf --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {} --footnotes --filescenesep".format(msdir, msfile, afile, ofile))

