#!/usr/bin/env python3

import os
import openms


print("Kicking tires ...")
openms.test.kick_tires()

# overall state
msdir  = "../example"
msfile = "manuscript.json"
afile  = "author.json"

# export docx
ofile  = "omstest_manuscript.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))

# export docx
ofile  = "omstest_manuscript_noquote-nosynopsis.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --exclude_tags quote synopsis --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))

# export docx
ofile  = "omstest_manuscript_simple.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --include_tags simple --exclude_tags quote synopsis --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))

# export docx
ofile  = "omstest_manuscript_notes.docx"
print("Running oms")
# msfile = "simple.json"
os.system("./oms --notes --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))

# export outline
ofile  = "omstest_outline.html"
print("Running oms2outline")
# msfile = "simple.json"
os.system("./oms2outline --manuscriptdir {} --manuscriptfile {} --authorfile {} --outputfile {}".format(msdir, msfile, afile, ofile))
