#!/usr/bin/env python3

# ---------------------------------------------------------------------------
#
# omsnext, a tool to get the next available scene number in a directory
#
# ---------------------------------------------------------------------------

import openms
import sys

if len(sys.argv) == 2:
    print(openms.core.get_next_scene(sys.argv[1]))
else:
    print("ERROR: need dirctory as argument")
